# Generated by Django 5.2.15 on 2026-09-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_initial_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalfarmerprofile',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
