# Generated by Django 5.2.15 on 2026-09-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_unique_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='operating_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='historicalfarmerprofile',
            name='operating_days',
            field=models.JSONField(default=list),
        ),
    ]
