# Generated by Django 5.2.15 on 2026-09-26 08:53

import marketlink_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_backfill_operating_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=marketlink_core.models.UUIDUploadTo('customers')),
        ),
    ]
