# Generated by Django 5.2.15 on 2026-09-26 17:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customerprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCustomerProfile',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('image', models.TextField(blank=True, max_length=255, null=True)),
                ('deactivation_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical customer profile',
                'verbose_name_plural': 'historical customer profiles',
                'db_table': 'customer_profile_histories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
