# Generated by Django 5.2.15 on 2026-09-24 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_collation="utf8mb4_0900_as_ci", max_length=50, unique=True
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "categories",
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to="products/"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("KG", "kg"),
                            ("BUNCH", "bó"),
                            ("PIECE", "quả/cái"),
                            ("PACK", "gói/hộp"),
                        ],
                        max_length=10,
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "weekly_default_quantity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_hidden_by_admin", models.BooleanField(default=False)),
                (
                    "hidden_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="accounts.farmerprofile",
                    ),
                ),
                (
                    "hidden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hidden_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["farmer", "is_archived"],
                        name="products_farmer_archived_idx",
                    ),
                    models.Index(
                        fields=["category", "is_archived", "is_hidden_by_admin"],
                        name="products_category_public_idx",
                    ),
                    models.Index(fields=["price"], name="products_price_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", 1000)),
                        name="products_price_min",
                    )
                ],
            },
        ),
    ]
