# Generated by Django 5.2.15 on 2026-09-24 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=1000)),
                ('audience', models.CharField(choices=[('ALL', 'All'), ('CUSTOMER', 'Customer'), ('FARMER', 'Farmer')], default='ALL', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['is_active', 'audience', 'starts_at'], name='ann_active_aud_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='ann_ends_after_starts')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('ORDER_ACCEPTED', 'Order Accepted'), ('ORDER_READY', 'Order Ready for Pickup'), ('ORDER_DECLINED', 'Order Declined'), ('ORDER_EXPIRED', 'Order Expired'), ('RESTOCK', 'Favorite Product Restocked'), ('ORDER_PLACED', 'New Order Placed'), ('ORDER_MODIFIED', 'Order Modified by Customer'), ('ORDER_CANCELLED', 'Order Cancelled by Customer'), ('ORDER_CANCELLED_CUSTOMER_LOCKED', 'Order Cancelled Due to Customer Lock'), ('ACCOUNT_STATUS_CHANGED', 'Account Status Changed'), ('MARKET_SCHEDULE_CHANGED', 'Market Schedule Changed')], max_length=40)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=500)),
                ('target_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notif_recipient_read_idx')],
            },
        ),
    ]
