# Generated by Django 5.2.15 on 2026-09-24 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("content", models.CharField(max_length=1000)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ALL", "Tất cả"),
                            ("CUSTOMER", "Khách hàng"),
                            ("FARMER", "Nông dân"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "announcements",
                "ordering": ("-starts_at",),
                "indexes": [
                    models.Index(
                        fields=["is_active", "audience", "starts_at"],
                        name="announcements_live_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ends_at__isnull", True),
                            ("ends_at__gt", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="announcements_ends_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ORDER_ACCEPTED", "Đơn đã được xác nhận"),
                            ("ORDER_READY", "Đơn sẵn sàng nhận"),
                            ("ORDER_DECLINED", "Đơn bị từ chối"),
                            ("ORDER_EXPIRED", "Đơn đã hết hạn"),
                            ("RESTOCK", "Sản phẩm yêu thích có hàng lại"),
                            ("ORDER_PLACED", "Đơn mới"),
                            ("ORDER_MODIFIED", "Khách sửa đơn"),
                            ("ORDER_CANCELLED", "Khách hủy đơn"),
                            (
                                "ORDER_CANCELLED_CUSTOMER_LOCKED",
                                "Đơn bị hủy do khách bị khóa",
                            ),
                            ("ACCOUNT_STATUS_CHANGED", "Trạng thái tài khoản thay đổi"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("message", models.CharField(max_length=500)),
                ("target_url", models.CharField(blank=True, max_length=255, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="notifications_inbox_idx",
                    )
                ],
            },
        ),
    ]
