# Generated by Django 5.2.15 on 2026-09-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_ACCEPTED', 'Order Accepted'), ('ORDER_READY', 'Order Ready for Pickup'), ('ORDER_DECLINED', 'Order Declined'), ('ORDER_EXPIRED', 'Order Expired'), ('ORDER_CHANGE_APPROVED', 'Order Change Request Approved'), ('ORDER_CHANGE_REJECTED', 'Order Change Request Rejected'), ('ORDER_ITEM_SOLD_OUT', 'Order Item Sold Out'), ('RESTOCK', 'Favorite Product Restocked'), ('ORDER_PLACED', 'New Order Placed'), ('ORDER_MODIFIED', 'Order Modified by Customer'), ('ORDER_CANCELLED', 'Order Cancelled by Customer'), ('ORDER_CANCELLED_CUSTOMER_LOCKED', 'Order Cancelled Due to Customer Lock'), ('ACCOUNT_STATUS_CHANGED', 'Account Status Changed'), ('MARKET_SCHEDULE_CHANGED', 'Market Schedule Changed'), ('MARKET_CLOSED', 'Market Closed')], max_length=40),
        ),
    ]
