# Generated by Django 5.2.15 on 2026-09-24 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
        ("markets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stall_label", models.CharField(blank=True, max_length=30, null=True)),
                ("pickup_date", models.DateField()),
                ("pickup_start_at", models.DateTimeField()),
                ("pickup_end_at", models.DateTimeField()),
                ("cutoff_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLACED", "Chờ duyệt"),
                            ("ACCEPTED", "Đã xác nhận"),
                            ("READY_FOR_PICKUP", "Sẵn sàng nhận"),
                            ("COMPLETED", "Hoàn tất"),
                            ("CANCELLED", "Đã hủy"),
                            ("DECLINED", "Bị từ chối"),
                            ("NO_SHOW", "Khách không đến"),
                            ("EXPIRED", "Đã hết hạn"),
                        ],
                        default="PLACED",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300, null=True)),
                ("total_amount", models.DecimalField(decimal_places=0, max_digits=12)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orders",
                        to="accounts.farmerprofile",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orders",
                        to="markets.market",
                    ),
                ),
                (
                    "pickup_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="markets.pickupslot",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_name", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=10)),
                ("unit_price", models.DecimalField(decimal_places=0, max_digits=12)),
                ("quantity", models.PositiveIntegerField()),
                ("line_total", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLACED", "Chờ duyệt"),
                            ("ACCEPTED", "Đã xác nhận"),
                            ("READY_FOR_PICKUP", "Sẵn sàng nhận"),
                            ("COMPLETED", "Hoàn tất"),
                            ("CANCELLED", "Đã hủy"),
                            ("DECLINED", "Bị từ chối"),
                            ("NO_SHOW", "Khách không đến"),
                            ("EXPIRED", "Đã hết hạn"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("PLACED", "Chờ duyệt"),
                            ("ACCEPTED", "Đã xác nhận"),
                            ("READY_FOR_PICKUP", "Sẵn sàng nhận"),
                            ("COMPLETED", "Hoàn tất"),
                            ("CANCELLED", "Đã hủy"),
                            ("DECLINED", "Bị từ chối"),
                            ("NO_SHOW", "Khách không đến"),
                            ("EXPIRED", "Đã hết hạn"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("T1", "Tạo đơn → PLACED"),
                            ("T2", "PLACED → ACCEPTED"),
                            ("T3", "PLACED → DECLINED"),
                            ("T4", "ACCEPTED → DECLINED"),
                            ("T5", "PLACED → CANCELLED"),
                            ("T6", "ACCEPTED → CANCELLED"),
                            ("T7", "ACCEPTED → PLACED"),
                            ("T8", "PLACED → EXPIRED"),
                            ("T9", "ACCEPTED → READY_FOR_PICKUP"),
                            ("T10", "READY_FOR_PICKUP → COMPLETED"),
                            ("T11", "READY_FOR_PICKUP → NO_SHOW"),
                            ("T12", "READY_FOR_PICKUP → DECLINED"),
                            ("T13", "READY_FOR_PICKUP → CANCELLED"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "actor_role",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Khách hàng"),
                            ("FARMER", "Nông dân"),
                            ("ADMIN", "Quản trị viên"),
                            ("SYSTEM", "Hệ thống"),
                        ],
                        max_length=20,
                    ),
                ),
                ("change_reason", models.TextField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=36, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_status_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_status_history",
                "ordering": ("order", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["farmer", "status", "pickup_start_at"],
                name="orders_farmer_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "status"], name="orders_customer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "farmer", "status"],
                name="orders_customer_farmer_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "pickup_start_at"], name="orders_status_pickup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["market", "status", "pickup_date"],
                name="orders_market_report_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("pickup_end_at__gt", models.F("pickup_start_at"))),
                name="orders_pickup_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("cutoff_at__lte", models.F("pickup_start_at"))),
                name="orders_cutoff_before_pickup",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="orders_total_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="order_items_unique_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="order_items_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="order_items_quantity_min",
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatushistory",
            index=models.Index(
                fields=["order", "created_at"], name="order_history_timeline_idx"
            ),
        ),
    ]
