# Generated by Django 5.2.15 on 2026-09-24 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stall_label', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_start_at', models.DateTimeField()),
                ('pickup_end_at', models.DateTimeField()),
                ('cutoff_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined'), ('NO_SHOW', 'No Show'), ('EXPIRED', 'Expired')], default='PLACED', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='accounts.farmerprofile')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='markets.market')),
                ('pickup_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='markets.pickupslot')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('BUNCH', 'Bunch'), ('PIECE', 'Piece'), ('PACK', 'Pack')], max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='catalog.product')),
            ],
            options={
                'db_table': 'order_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_status', models.CharField(blank=True, choices=[('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined'), ('NO_SHOW', 'No Show'), ('EXPIRED', 'Expired')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined'), ('NO_SHOW', 'No Show'), ('EXPIRED', 'Expired')], max_length=20)),
                ('transition', models.CharField(blank=True, choices=[('T1', 'Create Order'), ('T2', 'Approve Placed Order'), ('T3', 'Decline Placed Order'), ('T4', 'Decline Accepted Order'), ('T5', 'Customer Cancel Placed Order'), ('T6', 'Customer Cancel Accepted Order'), ('T7', 'Customer Modify Accepted Order'), ('T8', 'System Expire Order'), ('T9', 'Ready For Pickup'), ('T10', 'Complete Order'), ('T11', 'Mark No Show'), ('T12', 'Admin Suspend Farmer'), ('T13', 'Admin Lock Customer')], max_length=10, null=True)),
                ('actor_role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('FARMER', 'Farmer'), ('ADMIN', 'Administrator'), ('SYSTEM', 'System')], max_length=20)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=36, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_actions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'db_table': 'order_status_history',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['farmer', 'status', 'pickup_start_at'], name='ord_farmer_status_pick_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='ord_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'farmer', 'status'], name='ord_cust_farmer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'pickup_start_at'], name='ord_status_pick_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['market', 'status', 'pickup_date'], name='ord_market_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='ord_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_end_at__gt', models.F('pickup_start_at'))), name='ord_pickup_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('cutoff_at__lte', models.F('pickup_start_at'))), name='ord_cutoff_before_pickup'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='ord_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='oitem_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='oitem_uniq_order_product'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='oitem_quantity_min_1'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='oitem_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'created_at'], name='osh_order_created_idx'),
        ),
    ]
