# Generated by Django 5.2.15 on 2026-09-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_money_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_change',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='transition',
            field=models.CharField(blank=True, choices=[('T1', 'Create Order'), ('T2', 'Approve Placed Order'), ('T3', 'Decline Placed Order'), ('T4', 'Decline Accepted Order'), ('T5', 'Customer Cancel Placed Order'), ('T6', 'Customer Cancel Accepted Order'), ('T7', 'Deprecated - Customer Modify Accepted Order'), ('T8', 'System Expire Order'), ('T9', 'Ready For Pickup'), ('T10', 'Complete Order'), ('T11', 'Mark No Show'), ('T12', 'Admin Suspend Farmer'), ('T13', 'Admin Lock Customer'), ('T14', 'Mark No Show For Accepted Order')], max_length=10, null=True),
        ),
    ]
