# Generated by Django 5.2.15 on 2026-09-24 08:52

import django.core.validators
import django.db.models.deletion
import marketlink_core.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_collation='utf8mb4_0900_as_ci', max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=marketlink_core.models.UUIDUploadTo('markets'))),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('map_provider', models.CharField(default='OSM', max_length=30)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'markets',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='market_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('close_time__gt', models.F('open_time'))), name='market_close_after_open')],
            },
        ),
        migrations.CreateModel(
            name='FarmerMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stall_label', models.CharField(max_length=100)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_markets', to='accounts.farmerprofile')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='farmer_markets', to='markets.market')),
            ],
            options={
                'db_table': 'farmer_markets',
            },
        ),
        migrations.CreateModel(
            name='MarketClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='markets.market')),
            ],
            options={
                'db_table': 'market_closures',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketOperatingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_days', to='markets.market')),
            ],
            options={
                'db_table': 'market_operating_days',
                'ordering': ['market_id', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='PickupSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('farmer_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_slots', to='markets.farmermarket')),
            ],
            options={
                'db_table': 'pickup_slots',
                'ordering': ['farmer_market_id', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='FarmerClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='accounts.farmerprofile')),
            ],
            options={
                'db_table': 'farmer_closures',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['farmer', 'end_date'], name='fclosure_farmer_end_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='fclosure_end_after_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='farmermarket',
            constraint=models.UniqueConstraint(fields=('farmer', 'market'), name='fm_uniq_farmer_market'),
        ),
        migrations.AddIndex(
            model_name='marketclosure',
            index=models.Index(fields=['market', 'end_date'], name='mclosure_market_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketclosure',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='mclosure_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='marketoperatingday',
            index=models.Index(fields=['day_of_week'], name='mod_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketoperatingday',
            constraint=models.UniqueConstraint(fields=('market', 'day_of_week'), name='mod_uniq_market_day'),
        ),
        migrations.AddConstraint(
            model_name='marketoperatingday',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='mod_day_1_7'),
        ),
        migrations.AddConstraint(
            model_name='pickupslot',
            constraint=models.UniqueConstraint(fields=('farmer_market', 'day_of_week', 'start_time'), name='slot_uniq_fm_day_start'),
        ),
        migrations.AddConstraint(
            model_name='pickupslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='pickupslot',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='slot_day_1_7'),
        ),
    ]
