# Generated by Django 5.2.15 on 2026-09-24 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_collation="utf8mb4_0900_as_ci", max_length=100, unique=True
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to="markets/"
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("map_provider", models.CharField(default="OSM", max_length=30)),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "markets",
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["is_active"], name="markets_is_active_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("close_time__gt", models.F("open_time"))),
                        name="markets_close_after_open",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FarmerMarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stall_label", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_markets",
                        to="accounts.farmerprofile",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="farmer_markets",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "db_table": "farmer_markets",
            },
        ),
        migrations.CreateModel(
            name="MarketOperatingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Thứ 2"),
                            (2, "Thứ 3"),
                            (3, "Thứ 4"),
                            (4, "Thứ 5"),
                            (5, "Thứ 6"),
                            (6, "Thứ 7"),
                            (7, "Chủ nhật"),
                        ]
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_days",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "db_table": "market_operating_days",
                "ordering": ("market", "day_of_week"),
            },
        ),
        migrations.CreateModel(
            name="PickupSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Thứ 2"),
                            (2, "Thứ 3"),
                            (3, "Thứ 4"),
                            (4, "Thứ 5"),
                            (5, "Thứ 6"),
                            (6, "Thứ 7"),
                            (7, "Chủ nhật"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "farmer_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_slots",
                        to="markets.farmermarket",
                    ),
                ),
            ],
            options={
                "db_table": "pickup_slots",
                "ordering": ("farmer_market", "day_of_week", "start_time"),
            },
        ),
        migrations.AddConstraint(
            model_name="farmermarket",
            constraint=models.UniqueConstraint(
                fields=("farmer", "market"), name="farmer_markets_unique_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="marketoperatingday",
            index=models.Index(fields=["day_of_week"], name="market_days_day_idx"),
        ),
        migrations.AddConstraint(
            model_name="marketoperatingday",
            constraint=models.UniqueConstraint(
                fields=("market", "day_of_week"), name="market_days_unique_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketoperatingday",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_week__gte", 1), ("day_of_week__lte", 7)),
                name="market_days_day_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="pickupslot",
            constraint=models.UniqueConstraint(
                fields=("farmer_market", "day_of_week", "start_time"),
                name="pickup_slots_unique_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="pickupslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_week__gte", 1), ("day_of_week__lte", 7)),
                name="pickup_slots_day_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="pickupslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="pickup_slots_end_after_start",
            ),
        ),
    ]
