export const QUERY_KEYS = {
  ME: ['me'] as const,
  PUBLIC_CONFIG: ['public-config'] as const,
  CATEGORIES: ['categories'] as const,
  MARKETS: (params?: unknown) => ['markets', params] as const,
  MARKET: (id: string | number) => ['market', String(id)] as const,
  MARKET_FARMERS: (id: string | number) => ['market-farmers', String(id)] as const,
  FARMERS: (params?: unknown) => ['farmers', params] as const,
  FARMER: (id: string | number) => ['farmer', String(id)] as const,
  FARMER_PICKUP: (id: string | number) => ['farmer-pickup', String(id)] as const,
  FARMER_REVIEWS: (id: string | number) => ['farmer-reviews', String(id)] as const,
  FARMER_PRODUCTS: (id: string | number) => ['farmer-products', String(id)] as const,
  FARMER_RATING: (id: string | number) => ['farmer-rating', String(id)] as const,
  PRODUCTS: (params?: unknown) => ['products', params] as const,
  PRODUCT: (id: string | number) => ['product', String(id)] as const,
  PRODUCT_REVIEWS: (id: string | number) => ['product-reviews', String(id)] as const,
  PRODUCT_RATING: (id: string | number) => ['product-rating', String(id)] as const,
  SEARCH: (q: string) => ['search', q] as const,
  CUSTOMER_DASHBOARD: ['customer-dashboard'] as const,
  CUSTOMER_PROFILE: ['customer-profile'] as const,
  ORDERS: (params?: unknown) => ['orders', params] as const,
  ORDER: (id: string | number) => ['order', String(id)] as const,
  NOTIFICATIONS_LIST: ['notifications-list'] as const,
  FARMER_DASHBOARD: (params?: unknown) => ['farmer-dashboard', params] as const,
  FARMER_ORDER_COUNTS: ['farmer-order-counts'] as const,
  FARMER_ORDERS: (params?: unknown) => ['farmer-orders', params] as const,
  FARMER_ORDER: (id: string | number) => ['farmer-order', String(id)] as const,
  FARMER_PICKING: (date: string) => ['farmer-picking', date] as const,
  FARMER_MY_PRODUCTS: (params?: unknown) => ['farmer-my-products', params] as const,
  FARMER_MY_PRODUCT: (id: string | number) => ['farmer-my-product', String(id)] as const,
  FARMER_STOCK_PREVIEW: ['farmer-stock-preview'] as const,
  FARMER_MARKETS: ['farmer-markets'] as const,
  FARMER_PROFILE: ['farmer-profile'] as const,
  FARMER_MY_REVIEWS: (params?: unknown) => ['farmer-my-reviews', params] as const,
  ADMIN_DASHBOARD: ['admin-dashboard'] as const,
  ADMIN_FARMERS: (params?: unknown) => ['admin-farmers', params] as const,
  ADMIN_FARMER: (id: string | number) => ['admin-farmer', String(id)] as const,
  ADMIN_FARMER_IMPACT: (id: string | number) =>
    ['admin-farmer-impact', String(id)] as const,
  ADMIN_CUSTOMERS: (params?: unknown) => ['admin-customers', params] as const,
  ADMIN_CUSTOMER_IMPACT: (id: string | number) =>
    ['admin-customer-impact', String(id)] as const,
  ADMIN_CUSTOMER: (id: number) => ['admin-customer', id] as const,
  ADMIN_MARKETS: (params?: unknown) => ['admin-markets', params] as const,
  ADMIN_MARKET_CLOSURES: (marketId: number) =>
    ['admin-market-closures', marketId] as const,
  ADMIN_MARKET: (id: string | number) => ['admin-market', String(id)] as const,
  ADMIN_CATEGORIES: ['admin-categories'] as const,
  ADMIN_MODERATION_PRODUCTS: ['admin-mod-products'] as const,
  ADMIN_MODERATION_REVIEWS: ['admin-mod-reviews'] as const,
  ADMIN_REPORTS: (params?: unknown) => ['admin-reports', params] as const,
  ADMIN_ANNOUNCEMENTS: ['admin-announcements'] as const,
  ADMIN_AUDIT_LOGS: (params?: unknown) => ['admin-audit-logs', params] as const,
  ANNOUNCEMENTS: ['announcements'] as const,
  FAVORITE_IDS: ['favorite-ids'] as const,
  FAVORITE_MARKET: (id: string | number) => ['favorite-market', String(id)] as const,
  FAVORITE_FARMER: (id: string | number) => ['favorite-farmer', String(id)] as const,
  FAVORITE_PRODUCTS: (ids: unknown) => ['favorite-products', ids] as const,
};
