# Generated by Django 5.2.15 on 2026-09-24 08:52

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Change Password'), ('ACCESS_DENIED', 'Access Denied'), ('EXPORT_DATA', 'Export Data'), ('FARMER_APPROVED', 'Approve Farmer'), ('FARMER_REJECTED', 'Reject Farmer'), ('FARMER_SUSPENDED', 'Suspend Farmer'), ('FARMER_REINSTATED', 'Reinstate Farmer'), ('CUSTOMER_DEACTIVATED', 'Deactivate Customer'), ('CUSTOMER_ACTIVATED', 'Activate Customer'), ('PRODUCT_HIDDEN', 'Hide Product'), ('PRODUCT_RESTORED', 'Restore Product'), ('REVIEW_HIDDEN', 'Hide Review'), ('REVIEW_RESTORED', 'Restore Review')], max_length=40)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=36, null=True)),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_action_created_idx'), models.Index(fields=['user', 'created_at'], name='audit_user_created_idx'), models.Index(fields=['created_at'], name='audit_created_idx')],
            },
        ),
    ]
