# Generated by Django 5.2.15 on 2026-09-24 01:28

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Đăng nhập"),
                            ("LOGIN_FAILED", "Đăng nhập thất bại"),
                            ("LOGOUT", "Đăng xuất"),
                            ("PASSWORD_CHANGED", "Đổi mật khẩu"),
                            ("ACCESS_DENIED", "Truy cập trái quyền"),
                            ("EXPORT_DATA", "Xuất dữ liệu"),
                            ("FARMER_APPROVED", "Duyệt nông dân"),
                            ("FARMER_REJECTED", "Từ chối nông dân"),
                            ("FARMER_SUSPENDED", "Đình chỉ nông dân"),
                            ("FARMER_REINSTATED", "Khôi phục nông dân"),
                            ("CUSTOMER_DEACTIVATED", "Khóa khách hàng"),
                            ("CUSTOMER_ACTIVATED", "Kích hoạt khách hàng"),
                            ("PRODUCT_HIDDEN", "Gỡ sản phẩm"),
                            ("PRODUCT_RESTORED", "Khôi phục sản phẩm"),
                            ("REVIEW_HIDDEN", "Ẩn đánh giá"),
                            ("REVIEW_RESTORED", "Hiện lại đánh giá"),
                        ],
                        max_length=40,
                    ),
                ),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("method", models.CharField(blank=True, max_length=10, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("request_id", models.CharField(blank=True, max_length=36, null=True)),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"], name="audit_logs_action_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="audit_logs_user_idx"
                    ),
                ],
            },
        ),
    ]
