# Generated by Django 5.2.15 on 2026-09-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('ACCOUNT_REGISTERED', 'Account Registered'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Change Password'), ('ACCESS_DENIED', 'Access Denied'), ('EXPORT_DATA', 'Export Data'), ('FARMER_APPROVED', 'Approve Farmer'), ('FARMER_REJECTED', 'Reject Farmer'), ('FARMER_SUSPENDED', 'Suspend Farmer'), ('FARMER_REINSTATED', 'Reinstate Farmer'), ('CUSTOMER_DEACTIVATED', 'Deactivate Customer'), ('CUSTOMER_ACTIVATED', 'Activate Customer'), ('PRODUCT_HIDDEN', 'Hide Product'), ('PRODUCT_RESTORED', 'Restore Product'), ('REVIEW_HIDDEN', 'Hide Review'), ('REVIEW_RESTORED', 'Restore Review')], max_length=40),
        ),
    ]
