# Generated by Django 5.2.15 on 2026-09-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('ACCOUNT_REGISTERED', 'Account Registered'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Change Password'), ('ACCESS_DENIED', 'Access Denied'), ('EXPORT_DATA', 'Export Data'), ('FARMER_APPROVED', 'Approve Farmer'), ('FARMER_REJECTED', 'Reject Farmer'), ('FARMER_SUSPENDED', 'Suspend Farmer'), ('FARMER_REINSTATED', 'Reinstate Farmer'), ('CUSTOMER_DEACTIVATED', 'Deactivate Customer'), ('CUSTOMER_ACTIVATED', 'Activate Customer'), ('PRODUCT_HIDDEN', 'Hide Product'), ('PRODUCT_RESTORED', 'Restore Product'), ('REVIEW_HIDDEN', 'Hide Review'), ('REVIEW_RESTORED', 'Restore Review'), ('MARKET_CREATED', 'Create Market'), ('MARKET_UPDATED', 'Update Market'), ('MARKET_DEACTIVATED', 'Deactivate Market'), ('MARKET_ACTIVATED', 'Activate Market'), ('FARMER_UPDATED', 'Update Farmer Profile'), ('CUSTOMER_UPDATED', 'Update Customer Profile'), ('ACCOUNT_PURGED', 'Purge Stale Accounts')], max_length=40),
        ),
    ]
