# Generated by Django 5.2.15 on 2026-09-26 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('PRODUCT', 'Product'), ('FARMER_REVIEW', 'Farmer Review'), ('PRODUCT_REVIEW', 'Product Review'), ('FARMER', 'Farmer'), ('CUSTOMER', 'Customer')], max_length=20)),
                ('target_id', models.PositiveBigIntegerField()),
                ('note', models.CharField(max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=500, null=True)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_flags',
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='flag_target_idx'), models.Index(fields=['resolved_at'], name='flag_resolved_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('target_type', 'target_id'), name='one_open_flag_per_target')],
            },
        ),
    ]
