# Generated by Django 5.2.15 on 2026-09-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_auditlog_action'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='moderationflag',
            name='one_open_flag_per_target',
        ),
    ]
