# Generated by Django 5.2.15 on 2026-09-24 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('reply', models.CharField(blank=True, max_length=500, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('is_hidden_by_admin', models.BooleanField(default=False)),
                ('hidden_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_farmer_reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='farmer_review', to='orders.order')),
            ],
            options={
                'db_table': 'farmer_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_hidden_by_admin', 'created_at'], name='frev_hidden_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='frev_rating_1_5')],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('reply', models.CharField(blank=True, max_length=500, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('is_hidden_by_admin', models.BooleanField(default=False)),
                ('hidden_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_product_reviews', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='product_review', to='orders.orderitem')),
            ],
            options={
                'db_table': 'product_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_hidden_by_admin', 'created_at'], name='prev_hidden_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='prev_rating_1_5')],
            },
        ),
    ]
