# Generated by Django 5.2.15 on 2026-09-24 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_farmers', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favorited_by', to='accounts.farmerprofile')),
            ],
            options={
                'db_table': 'favorite_farmers',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'farmer'), name='favf_uniq_customer_farmer')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_markets', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favorited_by', to='markets.market')),
            ],
            options={
                'db_table': 'favorite_markets',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'market'), name='favm_uniq_customer_market')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favorited_by', to='catalog.product')),
            ],
            options={
                'db_table': 'favorite_products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='favp_product_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'product'), name='favp_uniq_customer_product')],
            },
        ),
    ]
